[modelling]
database = "covid19-model.sdb"

[modelling.training]
epochs = 5000
learning_rate = 0.01
regions = [
    "Canada:Alberta",
    "Canada:British Columbia",
    "Canada:Manitoba",
    "Canada:New Brunswick",
    "Canada:Newfoundland and Labrador",
    "Canada:Nova Scotia",
    "Canada:Ontario",
    "Canada:Prince Edward Island",
    "Canada:Quebec",
    "Canada:Saskatchewan"
]


[modelling.configuration]
lookahead_window = 1
initial_alpha = 0.95
hidden_states = 128
features = [
    "confirmed"
]
