name: Generate nightly report.

on:
  # Run this nightly at 9:00pm (EST).
  schedule:
    - cron: "0 1 * * *"

  # Also update anytime 'master' is updated.
  push:
    branches:
      - master

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Setup Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install the package and dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Generate the nightly report using the latest COVID-19 data.
      run: make report

    - name: Checkout the gh-pages branch in its own folder.
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Commit latest report to the gh-pages branch.
      run: |
        cp -R dist/* gh-pages
        ./scripts/update-gh-pages.sh
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
