name: Generate nightly report.

on:
  push:
    branches:
      - report-action

  # Run this nightly at 1:30am.
  schedule:
    - cron: "30 1 * * *"

  # Also allow it to be manually triggered.
  repository_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install the package and dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Generate the nightly report using the latest JHU CSSE data.
      run: |
        covid19 download
        covid19 report --dashboard --output index.html -c Canada -c US
    - name: Checkout the gh-pages branch in its own folder.
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit latest report to the gh-pages branch.
      run: |
        cp index.html gh-pages/index.html
        cp details-*.html gh-pages/.
        cd gh-pages
        ls
