name: Run case-rate Smoke Test

on: [ push ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run the unit tests.
      run: |
        pytest -v -rxXs .
    - name: Run a flake8 check
      run: |
        flake8 . --count --statistics
    - name: Check sources are pulled correctlly.
      run: |
        covid19 info
        covid19 info -c Canada
        covid19 info -c Canada:Ontario
    - name: Check analysis report can be generated.
      run: |
        covid19 analyze --min-confirmed 10 -c Canada
